#remote_theme: pages-themes/midnight@v0.2.0
#plugins:
#- jekyll-remote-theme
title: "Toby's Ramblings and Ruminations"
description: "Applying Quantitative Easing to the field of knowledge"
#show_downloads: false
layout: default
